/****** Object:  Table [dbo].[MovimientoArchivos]    Script Date: 15/04/2019 11:48:46 a.m. ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[MovimientoArchivos](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PATHFROM] [nvarchar](3000) NULL,
	[PATHTO] [nvarchar](3000) NULL,
	[FILENAME] [nvarchar](255) NULL,
	[PROCESSNAME] [nvarchar](255) NULL,
	[PROCESSNR] [int] NULL,
	[TRANSFERRED] [bit] NULL,
	[DOBACKUP] [bit] NULL,
	[CREATED_USER_ID] [bigint] NULL,
	[MODIFIED_USER_ID] [bigint] NULL,
	[CREATED_DATE] [datetime] NOT NULL,
	[MODIFIED_DATE] [datetime] NULL,
	[DELETED] [bit] NULL,
PRIMARY KEY NONCLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[MovimientoArchivos] ADD  DEFAULT ((0)) FOR [TRANSFERRED]
GO

ALTER TABLE [dbo].[MovimientoArchivos] ADD  DEFAULT ((0)) FOR [DOBACKUP]
GO

ALTER TABLE [dbo].[MovimientoArchivos] ADD  DEFAULT (getdate()) FOR [CREATED_DATE]
GO


