'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MovimientoArchivos
    Public Property Id As Long
    Public Property PathFrom As String
    Public Property PathTo As String
    Public Property FILENAME As String
    Public Property PROCESSNAME As String
    Public Property PROCESSNR As Nullable(Of Integer)
    Public Property TRANSFERRED As Nullable(Of Boolean)
    Public Property DOBACKUP As Nullable(Of Boolean)
    Public Property CREATED_USER_ID As Nullable(Of Long)
    Public Property MODIFIED_USER_ID As Nullable(Of Long)
    Public Property CREATED_DATE As Date
    Public Property MODIFIED_DATE As Nullable(Of Date)
    Public Property DELETED As Nullable(Of Boolean)

End Class
