'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class B_GeneralEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=B_GeneralEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Gen_Procesos() As DbSet(Of Gen_Procesos)
    Public Overridable Property Prov_DebitoDirecto() As DbSet(Of Prov_DebitoDirecto)

End Class
