'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Gen_Procesos
    Public Property Entidad As Short
    Public Property Sistema As Short
    Public Property Producto As Short
    Public Property Proceso As Integer
    Public Property DescProceso As String
    Public Property Habilitado As Nullable(Of Byte)
    Public Property Ejecuta As Nullable(Of Byte)
    Public Property Orden As Nullable(Of Short)
    Public Property Prioridad As Nullable(Of Short)
    Public Property Momento As String
    Public Property Periodicidad As String
    Public Property Externo As Nullable(Of Byte)
    Public Property Sigue As Nullable(Of Byte)
    Public Property Modulo As String
    Public Property Remoto As Nullable(Of Byte)
    Public Property APedido As Nullable(Of Byte)
    Public Property VsNet As Byte
    Public Property FecAudi As Nullable(Of Date)
    Public Property HorAudi As Nullable(Of Date)
    Public Property UsuAudi As String
    Public Property PrgAudi As String

End Class
