'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Procesos_TipoDireccionArchivo
    Public Property Id As Long
    Public Property Nombre As String
    Public Property Descripcion As String
    Public Property UsuarioCreacion As String
    Public Property FechaCreacion As Date
    Public Property UsuarioModificacion As String
    Public Property FechaModificacion As Nullable(Of Date)
    Public Property Eliminado As Nullable(Of Boolean)

    Public Overridable Property Procesos_OrigenDestinoArchivos As ICollection(Of Procesos_OrigenDestinoArchivos) = New HashSet(Of Procesos_OrigenDestinoArchivos)

End Class
