'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Procesos_TipoDireccionArchivo
    Public Property ID As Long
    Public Property NAME As String
    Public Property DESCRIPTION As String
    Public Property CREATED_USER_NAME As String
    Public Property CREATED_DATE As Date
    Public Property MODIFIED_USER_NAME As String
    Public Property MODIFIED_DATE As Nullable(Of Date)
    Public Property DELETED As Nullable(Of Boolean)

    Public Overridable Property Procesos_OrigenDestinoArchivos As ICollection(Of Procesos_OrigenDestinoArchivos) = New HashSet(Of Procesos_OrigenDestinoArchivos)

End Class
