'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Procesos_OrigenDestinoArchivos
    Public Property ID As Long
    Public Property PROCESSNR As Nullable(Of Integer)
    Public Property PATHFROM As String
    Public Property PATHTO As String
    Public Property CREATED_USER_ID As Nullable(Of Long)
    Public Property MODIFIED_USER_ID As Nullable(Of Long)
    Public Property CREATED_DATE As Date
    Public Property MODIFIED_DATE As Nullable(Of Date)
    Public Property DELETED As Nullable(Of Boolean)

    Public Overridable Property Procesos_MovimientoArchivos As ICollection(Of Procesos_MovimientoArchivos) = New HashSet(Of Procesos_MovimientoArchivos)

End Class
