'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Prov_DebitoDirecto
    Public Property FechaPres As Date
    Public Property IdArchivo As Decimal
    Public Property TipoArch As String
    Public Property CantD As Nullable(Of Integer)
    Public Property FechaEnvio As Nullable(Of Date)
    Public Property UsuarioEnvio As String
    Public Property NombreArchivo As String

End Class
